import 'package:auctus_call/views/salesman/main_catalog_screen.dart';
import 'package:auctus_call/views/salesman/profile_screen.dart';
import 'package:auctus_call/views/salesman/scraping_form.dart';
import 'package:flutter/material.dart';

class PlanCard extends StatelessWidget {
  final String title;
  final bool isSelected;
  final double width;
  final double height;

  const PlanCard({
    super.key,
    required this.title,
    this.isSelected = false,
    required this.width,
    required this.height,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: width,
      height: height,
      child: Card(
        color: isSelected ? Colors.blue[50] : Colors.white,
        elevation: isSelected ? 4.0 : 1.0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(10),
          side: BorderSide(
            color: isSelected ? Colors.blue : Colors.grey.shade300,
            width: 2,
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.all(10.0),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Icon(
                isSelected ? Icons.flash_on : Icons.payment,
                color: isSelected ? Colors.blue : Colors.grey,
              ),
              const SizedBox(width: 5),
              Text(
                title,
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  color: isSelected ? Colors.blue : Colors.black,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

List<String> beiersdorf = ['deodorant', 'body lotion', 'body serum', 'perfume'];

class Kabupaten {
  final String name;

  Kabupaten({required this.name});
}

List<String> categoryToko = [
  'Small',
  'Medium',
  'Large',
  'Enterprise',
];

class Province {
  final String name;
  final String capital;
  final List<Kabupaten> kabupatens;

  Province(
      {required this.name, required this.capital, required this.kabupatens});
}

final List<Province> provinces = [
  Province(
    name: 'Nanggroe Aceh Darussalam',
    capital: 'Banda Aceh',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Aceh Barat'),
      Kabupaten(name: 'Kabupaten Aceh Barat Daya'),
      Kabupaten(name: 'Kabupaten Aceh Besar'),
      Kabupaten(name: 'Kabupaten Aceh Jaya'),
      Kabupaten(name: 'Kabupaten Aceh Selatan'),
      Kabupaten(name: 'Kabupaten Aceh Singkil'),
      Kabupaten(name: 'Kabupaten Aceh Tamiang'),
      Kabupaten(name: 'Kabupaten Aceh Tengah'),
      Kabupaten(name: 'Kabupaten Aceh Tenggara'),
      Kabupaten(name: 'Kabupaten Aceh Timur'),
      Kabupaten(name: 'Kabupaten Aceh Utara'),
      Kabupaten(name: 'Kabupaten Bener Meriah'),
      Kabupaten(name: 'Kabupaten Bireuen'),
      Kabupaten(name: 'Kabupaten Gayo Lues'),
      Kabupaten(name: 'Kabupaten Nagan Raya'),
      Kabupaten(name: 'Kabupaten Pidie'),
      Kabupaten(name: 'Kabupaten Pidie Jaya'),
      Kabupaten(name: 'Kabupaten Simeulue'),
      Kabupaten(name: 'Kota Banda Aceh'),
      Kabupaten(name: 'Kota Langsa'),
      Kabupaten(name: 'Kota Lhokseumawe'),
      Kabupaten(name: 'Kota Sabang'),
      Kabupaten(name: 'Kota Subulussalam'),
    ],
  ),
  Province(
    name: 'Sumatera Utara',
    capital: 'Medan',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Asahan'),
      Kabupaten(name: 'Kabupaten Batubara'),
      Kabupaten(name: 'Kabupaten Dairi'),
      Kabupaten(name: 'Kabupaten Deli Serdang'),
      Kabupaten(name: 'Kabupaten Humbang Hasundutan'),
      Kabupaten(name: 'Kabupaten Karo'),
      Kabupaten(name: 'Kabupaten Labuhanbatu'),
      Kabupaten(name: 'Kabupaten Labuhanbatu Selatan'),
      Kabupaten(name: 'Kabupaten Labuhanbatu Utara'),
      Kabupaten(name: 'Kabupaten Langkat'),
      Kabupaten(name: 'Kabupaten Mandailing Natal'),
      Kabupaten(name: 'Kabupaten Nias'),
      Kabupaten(name: 'Kabupaten Nias Barat'),
      Kabupaten(name: 'Kabupaten Nias Selatan'),
      Kabupaten(name: 'Kabupaten Nias Utara'),
      Kabupaten(name: 'Kabupaten Padang Lawas'),
      Kabupaten(name: 'Kabupaten Padang Lawas Utara'),
      Kabupaten(name: 'Kabupaten Pakpak Bharat'),
      Kabupaten(name: 'Kabupaten Samosir'),
      Kabupaten(name: 'Kabupaten Serdang Bedagai'),
      Kabupaten(name: 'Kabupaten Simalungun'),
      Kabupaten(name: 'Kabupaten Tapanuli Selatan'),
      Kabupaten(name: 'Kabupaten Tapanuli Tengah'),
      Kabupaten(name: 'Kabupaten Tapanuli Utara'),
      Kabupaten(name: 'Kabupaten Toba Samosir'),
      Kabupaten(name: 'Kota Binjai'),
      Kabupaten(name: 'Kota Gunungsitoli'),
      Kabupaten(name: 'Kota Medan'),
      Kabupaten(name: 'Kota Padangsidempuan'),
      Kabupaten(name: 'Kota Pematangsiantar'),
      Kabupaten(name: 'Kota Sibolga'),
      Kabupaten(name: 'Kota Tanjungbalai'),
      Kabupaten(name: 'Kota Tebing Tinggi'),
    ],
  ),
  Province(
    name: 'Sumatera Selatan',
    capital: 'Palembang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Banyuasin'),
      Kabupaten(name: 'Kabupaten Empat Lawang'),
      Kabupaten(name: 'Kabupaten Lahat'),
      Kabupaten(name: 'Kabupaten Muara Enim'),
      Kabupaten(name: 'Kabupaten Musi Banyuasin'),
      Kabupaten(name: 'Kabupaten Musi Rawas'),
      Kabupaten(name: 'Kabupaten Musi Rawas Utara'),
      Kabupaten(name: 'Kabupaten Ogan Ilir'),
      Kabupaten(name: 'Kabupaten Ogan Komering Ilir'),
      Kabupaten(name: 'Kabupaten Ogan Komering Ulu'),
      Kabupaten(name: 'Kabupaten Ogan Komering Ulu Selatan'),
      Kabupaten(name: 'Kabupaten Ogan Komering Ulu Timur'),
      Kabupaten(name: 'Kabupaten Penukal Abab Lematang Ilir'),
      Kabupaten(name: 'Kota Lubuklinggau'),
      Kabupaten(name: 'Kota Pagar Alam'),
      Kabupaten(name: 'Kota Palembang'),
      Kabupaten(name: 'Kota Prabumulih'),
    ],
  ),
  Province(
    name: 'Sumatera Barat',
    capital: 'Padang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Agam'),
      Kabupaten(name: 'Kabupaten Dharmasraya'),
      Kabupaten(name: 'Kabupaten Kepulauan Mentawai'),
      Kabupaten(name: 'Kabupaten Lima Puluh Kota'),
      Kabupaten(name: 'Kabupaten Padang Pariaman'),
      Kabupaten(name: 'Kabupaten Pasaman'),
      Kabupaten(name: 'Kabupaten Pasaman Barat'),
      Kabupaten(name: 'Kabupaten Pesisir Selatan'),
      Kabupaten(name: 'Kabupaten Sijunjung'),
      Kabupaten(name: 'Kabupaten Solok'),
      Kabupaten(name: 'Kabupaten Solok Selatan'),
      Kabupaten(name: 'Kabupaten Tanah Datar'),
      Kabupaten(name: 'Kota Bukittinggi'),
      Kabupaten(name: 'Kota Padang'),
      Kabupaten(name: 'Kota Padangpanjang'),
      Kabupaten(name: 'Kota Pariaman'),
      Kabupaten(name: 'Kota Payakumbuh'),
      Kabupaten(name: 'Kota Sawahlunto'),
      Kabupaten(name: 'Kota Solok'),
    ],
  ),
  Province(
    name: 'Riau',
    capital: 'Pekanbaru',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bengkalis'),
      Kabupaten(name: 'Kabupaten Indragiri Hilir'),
      Kabupaten(name: 'Kabupaten Indragiri Hulu'),
      Kabupaten(name: 'Kabupaten Kampar'),
      Kabupaten(name: 'Kabupaten Kepulauan Meranti'),
      Kabupaten(name: 'Kabupaten Kuantan Singingi'),
      Kabupaten(name: 'Kabupaten Pelalawan'),
      Kabupaten(name: 'Kabupaten Rokan Hilir'),
      Kabupaten(name: 'Kabupaten Rokan Hulu'),
      Kabupaten(name: 'Kabupaten Siak'),
      Kabupaten(name: 'Kota Dumai'),
      Kabupaten(name: 'Kota Pekanbaru'),
    ],
  ),
  Province(
    name: 'Kepulauan Riau',
    capital: 'Tanjung Pinang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bintan'),
      Kabupaten(name: 'Kabupaten Karimun'),
      Kabupaten(name: 'Kabupaten Kepulauan Anambas'),
      Kabupaten(name: 'Kabupaten Lingga'),
      Kabupaten(name: 'Kabupaten Natuna'),
      Kabupaten(name: 'Kota Batam'),
      Kabupaten(name: 'Kota Tanjung Pinang'),
    ],
  ),
  Province(
    name: 'Jambi',
    capital: 'Jambi',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Batanghari'),
      Kabupaten(name: 'Kabupaten Bungo'),
      Kabupaten(name: 'Kabupaten Kerinci'),
      Kabupaten(name: 'Kabupaten Merangin'),
      Kabupaten(name: 'Kabupaten Muaro Jambi'),
      Kabupaten(name: 'Kabupaten Sarolangun'),
      Kabupaten(name: 'Kabupaten Tanjung Jabung Barat'),
      Kabupaten(name: 'Kabupaten Tanjung Jabung Timur'),
      Kabupaten(name: 'Kabupaten Tebo'),
      Kabupaten(name: 'Kota Jambi'),
      Kabupaten(name: 'Kota Sungai Penuh'),
    ],
  ),
  Province(
    name: 'Bengkulu',
    capital: 'Bengkulu',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bengkulu Selatan'),
      Kabupaten(name: 'Kabupaten Bengkulu Tengah'),
      Kabupaten(name: 'Kabupaten Bengkulu Utara'),
      Kabupaten(name: 'Kabupaten Kaur'),
      Kabupaten(name: 'Kabupaten Kepahiang'),
      Kabupaten(name: 'Kabupaten Lebong'),
      Kabupaten(name: 'Kabupaten Mukomuko'),
      Kabupaten(name: 'Kabupaten Rejang Lebong'),
      Kabupaten(name: 'Kabupaten Seluma'),
      Kabupaten(name: 'Kota Bengkulu'),
    ],
  ),
  Province(
    name: 'Bangka Belitung',
    capital: 'Pangkal Pinang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bangka'),
      Kabupaten(name: 'Kabupaten Bangka Barat'),
      Kabupaten(name: 'Kabupaten Bangka Selatan'),
      Kabupaten(name: 'Kabupaten Bangka Tengah'),
      Kabupaten(name: 'Kabupaten Belitung'),
      Kabupaten(name: 'Kabupaten Belitung Timur'),
      Kabupaten(name: 'Kota Pangkal Pinang'),
    ],
  ),
  Province(
    name: 'Lampung',
    capital: 'Bandar Lampung',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Lampung Tengah'),
      Kabupaten(name: 'Kabupaten Lampung Utara'),
      Kabupaten(name: 'Kabupaten Lampung Selatan'),
      Kabupaten(name: 'Kabupaten Lampung Barat'),
      Kabupaten(name: 'Kabupaten Lampung Timur'),
      Kabupaten(name: 'Kabupaten Mesuji'),
      Kabupaten(name: 'Kabupaten Pesawaran'),
      Kabupaten(name: 'Kabupaten Pesisir Barat'),
      Kabupaten(name: 'Kabupaten Pringsewu'),
      Kabupaten(name: 'Kabupaten Tulang Bawang'),
      Kabupaten(name: 'Kabupaten Tulang Bawang Barat'),
      Kabupaten(name: 'Kabupaten Tanggamus'),
      Kabupaten(name: 'Kabupaten Way Kanan'),
      Kabupaten(name: 'Kota Bandar Lampung'),
      Kabupaten(name: 'Kota Metro'),
    ],
  ),
  Province(
    name: 'Banten',
    capital: 'Serang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Lebak'),
      Kabupaten(name: 'Kabupaten Pandeglang'),
      Kabupaten(name: 'Kabupaten Serang'),
      Kabupaten(name: 'Kabupaten Tangerang'),
      Kabupaten(name: 'Kota Cilegon'),
      Kabupaten(name: 'Kota Serang'),
      Kabupaten(name: 'Kota Tangerang'),
      Kabupaten(name: 'Kota Tangerang Selatan'),
    ],
  ),
  Province(
    name: 'DKI Jakarta',
    capital: 'Jakarta',
    kabupatens: [
      Kabupaten(name: 'Kota Administrasi Jakarta Barat'),
      Kabupaten(name: 'Kota Administrasi Jakarta Pusat'),
      Kabupaten(name: 'Kota Administrasi Jakarta Selatan'),
      Kabupaten(name: 'Kota Administrasi Jakarta Timur'),
      Kabupaten(name: 'Kota Administrasi Jakarta Utara'),
      Kabupaten(name: 'Kabupaten Administrasi Kepulauan Seribu'),
    ],
  ),
  Province(
    name: 'Jawa Barat',
    capital: 'Bandung',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bandung'),
      Kabupaten(name: 'Kabupaten Bandung Barat'),
      Kabupaten(name: 'Kabupaten Bekasi'),
      Kabupaten(name: 'Kabupaten Bogor'),
      Kabupaten(name: 'Kabupaten Ciamis'),
      Kabupaten(name: 'Kabupaten Cianjur'),
      Kabupaten(name: 'Kabupaten Cirebon'),
      Kabupaten(name: 'Kabupaten Garut'),
      Kabupaten(name: 'Kabupaten Indramayu'),
      Kabupaten(name: 'Kabupaten Karawang'),
      Kabupaten(name: 'Kabupaten Kuningan'),
      Kabupaten(name: 'Kabupaten Majalengka'),
      Kabupaten(name: 'Kabupaten Pangandaran'),
      Kabupaten(name: 'Kabupaten Purwakarta'),
      Kabupaten(name: 'Kabupaten Subang'),
      Kabupaten(name: 'Kabupaten Sukabumi'),
      Kabupaten(name: 'Kabupaten Sumedang'),
      Kabupaten(name: 'Kabupaten Tasikmalaya'),
      Kabupaten(name: 'Kota Bandung'),
      Kabupaten(name: 'Kota Banjar'),
      Kabupaten(name: 'Kota Bekasi'),
      Kabupaten(name: 'Kota Bogor'),
      Kabupaten(name: 'Kota Cimahi'),
      Kabupaten(name: 'Kota Cirebon'),
      Kabupaten(name: 'Kota Depok'),
      Kabupaten(name: 'Kota Sukabumi'),
      Kabupaten(name: 'Kota Tasikmalaya'),
    ],
  ),
  Province(
    name: 'Jawa Tengah',
    capital: 'Semarang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Banjarnegara'),
      Kabupaten(name: 'Kabupaten Banyumas'),
      Kabupaten(name: 'Kabupaten Batang'),
      Kabupaten(name: 'Kabupaten Blora'),
      Kabupaten(name: 'Kabupaten Boyolali'),
      Kabupaten(name: 'Kabupaten Brebes'),
      Kabupaten(name: 'Kabupaten Cilacap'),
      Kabupaten(name: 'Kabupaten Demak'),
      Kabupaten(name: 'Kabupaten Grobogan'),
      Kabupaten(name: 'Kabupaten Jepara'),
      Kabupaten(name: 'Kabupaten Karanganyar'),
      Kabupaten(name: 'Kabupaten Kebumen'),
      Kabupaten(name: 'Kabupaten Kendal'),
      Kabupaten(name: 'Kabupaten Klaten'),
      Kabupaten(name: 'Kabupaten Kudus'),
      Kabupaten(name: 'Kabupaten Magelang'),
      Kabupaten(name: 'Kabupaten Pati'),
      Kabupaten(name: 'Kabupaten Pekalongan'),
      Kabupaten(name: 'Kabupaten Pemalang'),
      Kabupaten(name: 'Kabupaten Purbalingga'),
      Kabupaten(name: 'Kabupaten Purworejo'),
      Kabupaten(name: 'Kabupaten Rembang'),
      Kabupaten(name: 'Kabupaten Semarang'),
      Kabupaten(name: 'Kabupaten Sragen'),
      Kabupaten(name: 'Kabupaten Sukoharjo'),
      Kabupaten(name: 'Kabupaten Tegal'),
      Kabupaten(name: 'Kabupaten Temanggung'),
      Kabupaten(name: 'Kabupaten Wonogiri'),
      Kabupaten(name: 'Kabupaten Wonosobo'),
      Kabupaten(name: 'Kota Magelang'),
      Kabupaten(name: 'Kota Pekalongan'),
      Kabupaten(name: 'Kota Salatiga'),
      Kabupaten(name: 'Kota Semarang'),
      Kabupaten(name: 'Kota Surakarta'),
      Kabupaten(name: 'Kota Tegal'),
    ],
  ),
  Province(
    name: 'Daerah Istimewa Yogyakarta',
    capital: 'Yogyakarta',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bantul'),
      Kabupaten(name: 'Kabupaten Gunungkidul'),
      Kabupaten(name: 'Kabupaten Kulon Progo'),
      Kabupaten(name: 'Kabupaten Sleman'),
      Kabupaten(name: 'Kota Yogyakarta'),
    ],
  ),
  Province(
    name: 'Jawa Timur',
    capital: 'Surabaya',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bangkalan'),
      Kabupaten(name: 'Kabupaten Banyuwangi'),
      Kabupaten(name: 'Kabupaten Blitar'),
      Kabupaten(name: 'Kabupaten Bojonegoro'),
      Kabupaten(name: 'Kabupaten Bondowoso'),
      Kabupaten(name: 'Kabupaten Gresik'),
      Kabupaten(name: 'Kabupaten Jember'),
      Kabupaten(name: 'Kabupaten Jombang'),
      Kabupaten(name: 'Kabupaten Kediri'),
      Kabupaten(name: 'Kabupaten Lamongan'),
      Kabupaten(name: 'Kabupaten Lumajang'),
      Kabupaten(name: 'Kabupaten Madiun'),
      Kabupaten(name: 'Kabupaten Magetan'),
      Kabupaten(name: 'Kabupaten Malang'),
      Kabupaten(name: 'Kabupaten Mojokerto'),
      Kabupaten(name: 'Kabupaten Nganjuk'),
      Kabupaten(name: 'Kabupaten Ngawi'),
      Kabupaten(name: 'Kabupaten Pacitan'),
      Kabupaten(name: 'Kabupaten Pamekasan'),
      Kabupaten(name: 'Kabupaten Pasuruan'),
      Kabupaten(name: 'Kabupaten Ponorogo'),
      Kabupaten(name: 'Kabupaten Probolinggo'),
      Kabupaten(name: 'Kabupaten Sampang'),
      Kabupaten(name: 'Kabupaten Sidoarjo'),
      Kabupaten(name: 'Kabupaten Situbondo'),
      Kabupaten(name: 'Kabupaten Sumenep'),
      Kabupaten(name: 'Kabupaten Trenggalek'),
      Kabupaten(name: 'Kabupaten Tuban'),
      Kabupaten(name: 'Kabupaten Tulungagung'),
      Kabupaten(name: 'Kota Batu'),
      Kabupaten(name: 'Kota Blitar'),
      Kabupaten(name: 'Kota Kediri'),
      Kabupaten(name: 'Kota Madiun'),
      Kabupaten(name: 'Kota Malang'),
      Kabupaten(name: 'Kota Mojokerto'),
      Kabupaten(name: 'Kota Pasuruan'),
      Kabupaten(name: 'Kota Probolinggo'),
      Kabupaten(name: 'Kota Surabaya'),
    ],
  ),
  Province(
    name: 'Bali',
    capital: 'Denpasar',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Badung'),
      Kabupaten(name: 'Kabupaten Bangli'),
      Kabupaten(name: 'Kabupaten Buleleng'),
      Kabupaten(name: 'Kabupaten Gianyar'),
      Kabupaten(name: 'Kabupaten Jembrana'),
      Kabupaten(name: 'Kabupaten Karangasem'),
      Kabupaten(name: 'Kabupaten Klungkung'),
      Kabupaten(name: 'Kabupaten Tabanan'),
      Kabupaten(name: 'Kota Denpasar'),
    ],
  ),
  Province(
    name: 'Nusa Tenggara Barat',
    capital: 'Mataram',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bima'),
      Kabupaten(name: 'Kabupaten Dompu'),
      Kabupaten(name: 'Kabupaten Lombok Barat'),
      Kabupaten(name: 'Kabupaten Lombok Tengah'),
      Kabupaten(name: 'Kabupaten Lombok Timur'),
      Kabupaten(name: 'Kabupaten Lombok Utara'),
      Kabupaten(name: 'Kabupaten Sumbawa'),
      Kabupaten(name: 'Kabupaten Sumbawa Barat'),
      Kabupaten(name: 'Kota Bima'),
      Kabupaten(name: 'Kota Mataram'),
    ],
  ),
  Province(
    name: 'Nusa Tenggara Timur',
    capital: 'Kupang',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Alor'),
      Kabupaten(name: 'Kabupaten Belu'),
      Kabupaten(name: 'Kabupaten Ende'),
      Kabupaten(name: 'Kabupaten Flores Timur'),
      Kabupaten(name: 'Kabupaten Kupang'),
      Kabupaten(name: 'Kabupaten Lembata'),
      Kabupaten(name: 'Kabupaten Malaka'),
      Kabupaten(name: 'Kabupaten Manggarai'),
      Kabupaten(name: 'Kabupaten Manggarai Barat'),
      Kabupaten(name: 'Kabupaten Manggarai Timur'),
      Kabupaten(name: 'Kabupaten Ngada'),
      Kabupaten(name: 'Kabupaten Nagekeo'),
      Kabupaten(name: 'Kabupaten Rote Ndao'),
      Kabupaten(name: 'Kabupaten Sabu Raijua'),
      Kabupaten(name: 'Kabupaten Sikka'),
      Kabupaten(name: 'Kabupaten Sumba Barat'),
      Kabupaten(name: 'Kabupaten Sumba Barat Daya'),
      Kabupaten(name: 'Kabupaten Sumba Tengah'),
      Kabupaten(name: 'Kabupaten Sumba Timur'),
      Kabupaten(name: 'Kabupaten Timor Tengah Selatan'),
      Kabupaten(name: 'Kabupaten Timor Tengah Utara'),
      Kabupaten(name: 'Kota Kupang'),
    ],
  ),
  Province(
    name: 'Kalimantan Barat',
    capital: 'Pontianak',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bengkayang'),
      Kabupaten(name: 'Kabupaten Kapuas Hulu'),
      Kabupaten(name: 'Kabupaten Kayong Utara'),
      Kabupaten(name: 'Kabupaten Ketapang'),
      Kabupaten(name: 'Kabupaten Kubu Raya'),
      Kabupaten(name: 'Kabupaten Landak'),
      Kabupaten(name: 'Kabupaten Melawi'),
      Kabupaten(name: 'Kabupaten Mempawah'),
      Kabupaten(name: 'Kabupaten Sambas'),
      Kabupaten(name: 'Kabupaten Sanggau'),
      Kabupaten(name: 'Kabupaten Sekadau'),
      Kabupaten(name: 'Kabupaten Sintang'),
      Kabupaten(name: 'Kota Pontianak'),
      Kabupaten(name: 'Kota Singkawang'),
    ],
  ),
  Province(
    name: 'Kalimantan Selatan',
    capital: 'Banjarbaru',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Balangan'),
      Kabupaten(name: 'Kabupaten Banjar'),
      Kabupaten(name: 'Kabupaten Barito Kuala'),
      Kabupaten(name: 'Kabupaten Hulu Sungai Selatan'),
      Kabupaten(name: 'Kabupaten Hulu Sungai Tengah'),
      Kabupaten(name: 'Kabupaten Hulu Sungai Utara'),
      Kabupaten(name: 'Kabupaten Kotabaru'),
      Kabupaten(name: 'Kabupaten Tabalong'),
      Kabupaten(name: 'Kabupaten Tanah Bumbu'),
      Kabupaten(name: 'Kabupaten Tanah Laut'),
      Kabupaten(name: 'Kabupaten Tapin'),
      Kabupaten(name: 'Kota Banjarbaru'),
      Kabupaten(name: 'Kota Banjarmasin'),
    ],
  ),
  Province(
    name: 'Kalimantan Tengah',
    capital: 'Palangkaraya',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Barito Selatan'),
      Kabupaten(name: 'Kabupaten Barito Timur'),
      Kabupaten(name: 'Kabupaten Barito Utara'),
      Kabupaten(name: 'Kabupaten Gunung Mas'),
      Kabupaten(name: 'Kabupaten Kapuas'),
      Kabupaten(name: 'Kabupaten Katingan'),
      Kabupaten(name: 'Kabupaten Kotawaringin Barat'),
      Kabupaten(name: 'Kabupaten Kotawaringin Timur'),
      Kabupaten(name: 'Kabupaten Lamandau'),
      Kabupaten(name: 'Kabupaten Murung Raya'),
      Kabupaten(name: 'Kabupaten Pulang Pisau'),
      Kabupaten(name: 'Kabupaten Sukamara'),
      Kabupaten(name: 'Kabupaten Seruyan'),
      Kabupaten(name: 'Kota Palangka Raya'),
    ],
  ),
  Province(
    name: 'Kalimantan Timur',
    capital: 'Samarinda',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Berau'),
      Kabupaten(name: 'Kabupaten Kutai Barat'),
      Kabupaten(name: 'Kabupaten Kutai Kartanegara'),
      Kabupaten(name: 'Kabupaten Kutai Timur'),
      Kabupaten(name: 'Kabupaten Mahakam Ulu'),
      Kabupaten(name: 'Kabupaten Paser'),
      Kabupaten(name: 'Kabupaten Penajam Paser Utara'),
      Kabupaten(name: 'Kota Balikpapan'),
      Kabupaten(name: 'Kota Bontang'),
      Kabupaten(name: 'Kota Samarinda'),
    ],
  ),
  Province(
    name: 'Kalimantan Utara',
    capital: 'Tanjung Selor',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bulungan'),
      Kabupaten(name: 'Kabupaten Malinau'),
      Kabupaten(name: 'Kabupaten Nunukan'),
      Kabupaten(name: 'Kabupaten Tana Tidung'),
      Kabupaten(name: 'Kota Tarakan'),
    ],
  ),
  Province(
    name: 'Gorontalo',
    capital: 'Gorontalo',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Boalemo'),
      Kabupaten(name: 'Kabupaten Bone Bolango'),
      Kabupaten(name: 'Kabupaten Gorontalo'),
      Kabupaten(name: 'Kabupaten Gorontalo Utara'),
      Kabupaten(name: 'Kabupaten Pohuwato'),
      Kabupaten(name: 'Kota Gorontalo'),
    ],
  ),
  Province(
    name: 'Sulawesi Selatan',
    capital: 'Makassar',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bantaeng'),
      Kabupaten(name: 'Kabupaten Barru'),
      Kabupaten(name: 'Kabupaten Bone'),
      Kabupaten(name: 'Kabupaten Bulukumba'),
      Kabupaten(name: 'Kabupaten Enrekang'),
      Kabupaten(name: 'Kabupaten Gowa'),
      Kabupaten(name: 'Kabupaten Jeneponto'),
      Kabupaten(name: 'Kabupaten Kepulauan Selayar'),
      Kabupaten(name: 'Kabupaten Luwu'),
      Kabupaten(name: 'Kabupaten Luwu Timur'),
      Kabupaten(name: 'Kabupaten Luwu Utara'),
      Kabupaten(name: 'Kabupaten Maros'),
      Kabupaten(name: 'Kabupaten Pangkajene dan Kepulauan'),
      Kabupaten(name: 'Kabupaten Pinrang'),
      Kabupaten(name: 'Kabupaten Sidenreng Rappang'),
      Kabupaten(name: 'Kabupaten Sinjai'),
      Kabupaten(name: 'Kabupaten Soppeng'),
      Kabupaten(name: 'Kabupaten Takalar'),
      Kabupaten(name: 'Kabupaten Tana Toraja'),
      Kabupaten(name: 'Kabupaten Toraja Utara'),
      Kabupaten(name: 'Kabupaten Wajo'),
      Kabupaten(name: 'Kota Makassar'),
      Kabupaten(name: 'Kota Palopo'),
      Kabupaten(name: 'Kota Parepare'),
    ],
  ),
  Province(
    name: 'Sulawesi Tenggara',
    capital: 'Kendari',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bombana'),
      Kabupaten(name: 'Kabupaten Buton'),
      Kabupaten(name: 'Kabupaten Buton Selatan'),
      Kabupaten(name: 'Kabupaten Buton Tengah'),
      Kabupaten(name: 'Kabupaten Buton Utara'),
      Kabupaten(name: 'Kabupaten Kolaka'),
      Kabupaten(name: 'Kabupaten Kolaka Timur'),
      Kabupaten(name: 'Kabupaten Kolaka Utara'),
      Kabupaten(name: 'Kabupaten Konawe'),
      Kabupaten(name: 'Kabupaten Konawe Kepulauan'),
      Kabupaten(name: 'Kabupaten Konawe Selatan'),
      Kabupaten(name: 'Kabupaten Konawe Utara'),
      Kabupaten(name: 'Kabupaten Muna'),
      Kabupaten(name: 'Kabupaten Muna Barat'),
      Kabupaten(name: 'Kabupaten Wakatobi'),
      Kabupaten(name: 'Kota Bau-Bau'),
      Kabupaten(name: 'Kota Kendari'),
    ],
  ),
  Province(
    name: 'Sulawesi Tengah',
    capital: 'Palu',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Banggai'),
      Kabupaten(name: 'Kabupaten Banggai Kepulauan'),
      Kabupaten(name: 'Kabupaten Banggai Laut'),
      Kabupaten(name: 'Kabupaten Buol'),
      Kabupaten(name: 'Kabupaten Donggala'),
      Kabupaten(name: 'Kabupaten Morowali'),
      Kabupaten(name: 'Kabupaten Morowali Utara'),
      Kabupaten(name: 'Kabupaten Parigi Moutong'),
      Kabupaten(name: 'Kabupaten Poso'),
      Kabupaten(name: 'Kabupaten Sigi'),
      Kabupaten(name: 'Kabupaten Tojo Una-Una'),
      Kabupaten(name: 'Kabupaten Toli-Toli'),
      Kabupaten(name: 'Kota Palu'),
    ],
  ),
  Province(
    name: 'Sulawesi Utara',
    capital: 'Manado',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Bolaang Mongondow'),
      Kabupaten(name: 'Kabupaten Bolaang Mongondow Selatan'),
      Kabupaten(name: 'Kabupaten Bolaang Mongondow Timur'),
      Kabupaten(name: 'Kabupaten Bolaang Mongondow Utara'),
      Kabupaten(name: 'Kabupaten Kepulauan Sangihe'),
      Kabupaten(name: 'Kabupaten Kepulauan Siau Tagulandang Biaro'),
      Kabupaten(name: 'Kabupaten Kepulauan Talaud'),
      Kabupaten(name: 'Kabupaten Minahasa'),
      Kabupaten(name: 'Kabupaten Minahasa Selatan'),
      Kabupaten(name: 'Kabupaten Minahasa Tenggara'),
      Kabupaten(name: 'Kabupaten Minahasa Utara'),
      Kabupaten(name: 'Kota Bitung'),
      Kabupaten(name: 'Kota Kotamobagu'),
      Kabupaten(name: 'Kota Manado'),
      Kabupaten(name: 'Kota Tomohon'),
    ],
  ),
  Province(
    name: 'Sulawesi Barat',
    capital: 'Mamuju',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Majene'),
      Kabupaten(name: 'Kabupaten Mamasa'),
      Kabupaten(name: 'Kabupaten Mamuju'),
      Kabupaten(name: 'Kabupaten Mamuju Tengah'),
      Kabupaten(name: 'Kabupaten Mamuju Utara'),
      Kabupaten(name: 'Kabupaten Polewali Mandar'),
    ],
  ),
  Province(
    name: 'Maluku Utara',
    capital: 'Sofifi',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Halmahera Barat'),
      Kabupaten(name: 'Kabupaten Halmahera Tengah'),
      Kabupaten(name: 'Kabupaten Halmahera Utara'),
      Kabupaten(name: 'Kabupaten Halmahera Selatan'),
      Kabupaten(name: 'Kabupaten Kepulauan Sula'),
      Kabupaten(name: 'Kabupaten Halmahera Timur'),
      Kabupaten(name: 'Kabupaten Pulau Morotai'),
      Kabupaten(name: 'Kabupaten Pulau Taliabu'),
      Kabupaten(name: 'Kota Ternate'),
      Kabupaten(name: 'Kota Tidore Kepulauan'),
    ],
  ),
  Province(
    name: 'Maluku',
    capital: 'Ambon',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Buru'),
      Kabupaten(name: 'Kabupaten Buru Selatan'),
      Kabupaten(name: 'Kabupaten Kepulauan Aru'),
      Kabupaten(name: 'Kabupaten Maluku Barat Daya'),
      Kabupaten(name: 'Kabupaten Maluku Tengah'),
      Kabupaten(name: 'Kabupaten Maluku Tenggara'),
      Kabupaten(name: 'Kabupaten Maluku Tenggara Barat'),
      Kabupaten(name: 'Kabupaten Seram Bagian Barat'),
      Kabupaten(name: 'Kabupaten Seram Bagian Timur'),
      Kabupaten(name: 'Kota Ambon'),
      Kabupaten(name: 'Kota Tual'),
    ],
  ),
  Province(
    name: 'Papua Barat',
    capital: 'Manokwari',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Fakfak'),
      Kabupaten(name: 'Kabupaten Kaimana'),
      Kabupaten(name: 'Kabupaten Manokwari'),
      Kabupaten(name: 'Kabupaten Manokwari Selatan'),
      Kabupaten(name: 'Kabupaten Maybrat'),
      Kabupaten(name: 'Kabupaten Pegunungan Arfak'),
      Kabupaten(name: 'Kabupaten Raja Ampat'),
      Kabupaten(name: 'Kabupaten Sorong'),
      Kabupaten(name: 'Kabupaten Sorong Selatan'),
      Kabupaten(name: 'Kabupaten Tambrauw'),
      Kabupaten(name: 'Kabupaten Teluk Bintuni'),
      Kabupaten(name: 'Kabupaten Teluk Wondama'),
    ],
  ),
  Province(
    name: 'Papua',
    capital: 'Jayapura',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Asmat'),
      Kabupaten(name: 'Kabupaten Biak Numfor'),
      Kabupaten(name: 'Kabupaten Boven Digoel'),
      Kabupaten(name: 'Kabupaten Deiyai'),
      Kabupaten(name: 'Kabupaten Dogiyai'),
      Kabupaten(name: 'Kabupaten Intan Jaya'),
      Kabupaten(name: 'Kabupaten Jayapura'),
      Kabupaten(name: 'Kabupaten Jayawijaya'),
      Kabupaten(name: 'Kabupaten Keerom'),
      Kabupaten(name: 'Kabupaten Kepulauan Yapen'),
      Kabupaten(name: 'Kabupaten Lanny Jaya'),
      Kabupaten(name: 'Kabupaten Mamberamo Raya'),
      Kabupaten(name: 'Kabupaten Mamberamo Tengah'),
      Kabupaten(name: 'Kabupaten Mappi'),
      Kabupaten(name: 'Kabupaten Merauke'),
      Kabupaten(name: 'Kabupaten Mimika'),
      Kabupaten(name: 'Kabupaten Nabire'),
      Kabupaten(name: 'Kabupaten Nduga'),
      Kabupaten(name: 'Kabupaten Paniai'),
      Kabupaten(name: 'Kabupaten Pegunungan Bintang'),
      Kabupaten(name: 'Kabupaten Puncak'),
      Kabupaten(name: 'Kabupaten Puncak Jaya'),
      Kabupaten(name: 'Kabupaten Sarmi'),
      Kabupaten(name: 'Kabupaten Supiori'),
      Kabupaten(name: 'Kabupaten Tolikara'),
      Kabupaten(name: 'Kabupaten Waropen'),
      Kabupaten(name: 'Kabupaten Yahukimo'),
      Kabupaten(name: 'Kabupaten Yalimo'),
      Kabupaten(name: 'Kota Jayapura'),
    ],
  ),
  Province(
    name: 'Papua Tengah',
    capital: 'Nabire',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Nabire'),
      Kabupaten(name: 'Kabupaten Paniai'),
      Kabupaten(name: 'Kabupaten Mimika'),
      Kabupaten(name: 'Kabupaten Intan Jaya'),
      Kabupaten(name: 'Kabupaten Puncak'),
    ],
  ),
  Province(
    name: 'Papua Pegunungan',
    capital: 'Jayawijaya',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Jayawijaya'),
      Kabupaten(name: 'Kabupaten Lanny Jaya'),
      Kabupaten(name: 'Kabupaten Mamberamo Tengah'),
      Kabupaten(name: 'Kabupaten Nduga'),
      Kabupaten(name: 'Kabupaten Tolikara'),
      Kabupaten(name: 'Kabupaten Yahukimo'),
      Kabupaten(name: 'Kabupaten Yalimo'),
      Kabupaten(name: 'Kabupaten Pegunungan Bintang'),
    ],
  ),
  Province(
    name: 'Papua Selatan',
    capital: 'Merauke',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Merauke'),
      Kabupaten(name: 'Kabupaten Boven Digoel'),
      Kabupaten(name: 'Kabupaten Mappi'),
      Kabupaten(name: 'Kabupaten Asmat'),
    ],
  ),
  Province(
    name: 'Papua Barat Daya',
    capital: 'Sorong',
    kabupatens: [
      Kabupaten(name: 'Kabupaten Sorong'),
      Kabupaten(name: 'Kabupaten Sorong Selatan'),
      Kabupaten(name: 'Kabupaten Raja Ampat'),
      Kabupaten(name: 'Kabupaten Tambrauw'),
      Kabupaten(name: 'Kabupaten Maybrat'),
      Kabupaten(name: 'Kota Sorong'),
    ],
  ),
];
